version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: cueta_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: python_bot
    environment:
      - DB_NAME=cueta_database
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=1111
    depends_on:
      - postgres

volumes:
  postgres_data:
